### ISSUE TITLE
issue getting into cockpits

### ISSUE THREAD

**Issue by evilking9090** [DraconisCluster/DracVerse-Issues#11]
**Describe the bug**
Issue getting into standard cockpit, when entering immediately gets disconnected. 

**To Reproduce**
1. Get in Cockpit
2. Get disconnected

**Expected behavior**
get in and out without being disconnected

**Instance#:**
DV5

**Additional context**
attempted to grind down the cockpit as per usual keen jank, didn't resolve the issue.
When coded cut/paste the grid back in, it resolved the issue.

Grid was built using a workshop bp, when attempting to /fixship i received message "Grid seems to be owned by a different player."

**Comment by Tactech1157** [comment]
To add to this...
I'm having the same issue with the dlc control seat.
Once entering I get disconnected, once logged back on I'll be sitting in the seat and can leave just fine, will just crash if I get back in it though.
Not experiencing this with the standard cockpits

**Comment by Synirrr** [comment]
Issue fixed itself
