### ISSUE TITLE
Hot bar reset after restart

### ISSUE THREAD

**Issue by Joyfulasteroid** [DraconisCluster/DracVerse-Issues#12]
Set up my hotbar as I got start, restart occured. After coming back from restart my hotbar has been reset to how it was when I first loaded in.

Instance: DV7
Screen shot of what the hotbar defaulted to
![Screenshot_217](https://user-images.githubusercontent.com/79765295/167255868-a53c583c-f9eb-4717-bccc-0f2a8dea61d3.png)

**Comment by Joyfulasteroid** [comment]
Had this happen again today

**Comment by Synirrr** [comment]
If it happens again after release please raise another issue. At this time I am unable to reproduce it.
