### ISSUE TITLE
DV8 hangar "not enabled"

### ISSUE THREAD

**Issue by Wraith-54** [DraconisCluster/DracVerse-Issues#131]
**Describe the bug**
received a ticket, player not able to extract grid from hanger 

**To Reproduce**
go to crait, 
attempt to run !h load *
see error message

**Expected behavior**

**Screenshots**

**Instance#:**

**Additional context**
!hm works as does !h list
coded recently cleared space on the hard drive as the box was full. unknown if any causality or just coincidence

**Comment by kontu** [comment]
fixed next reboot
