### ISSUE TITLE
Unable to place second core

### ISSUE THREAD

**Issue by taiyoko** [DraconisCluster/DracVerse-Issues#15]
**Describe the bug**
While there is a basic core on the grid, I was unable to place a second core - I had to grind off the existing and then re-place it.

**To Reproduce**
1. Have a grid with an existing basic core
2. Attempt to place a second core

**Expected behavior**
I believed I could place a second core and the grid would be non functional until there was only one core on the grid, then welded up.

**Screenshots**
![corebug](https://user-images.githubusercontent.com/2172235/167262543-ee9dde7b-1f95-4fc5-ab30-6872bac91e46.png)

**Instance#:**
DV4

**Comment by evilking9090** [comment]
I believe this is intended behavior.

**Comment by TheCodedOne** [comment]
This is intended behaviour.
