### ISSUE TITLE
Iron is Very Hard to Come By Early Game

### ISSUE THREAD

**Issue by dariencupit** [DraconisCluster/DracVerse-Issues#21]
With the low stone->iron refine rates and hard to find iron-ore veins, I have found myself grinding stone for hours upon hours just to get enough steel plates necessary for a small grid production core. I dont think assemblers/refiners need a flat increase, but I do think something should be done about early game iron.

**Comment by Synirrr** [comment]
Fixed with updated vanilla recipes
