### ISSUE TITLE
Ore Voxel Rock Bug

### ISSUE THREAD

**Issue by kyde23** [DraconisCluster/DracVerse-Issues#23]
**Describe the bug**
2 ores spawned in one voxel rock on vali.
**To Reproduce**
1. Go to GPS:Gold and mag combo:-18355741.52:-18442049.75:14951124.02:#FF75C9F1:
**Expected behavior**
1 ore spawning in the 1 rock.

**Screenshots**
https://cdn.discordapp.com/attachments/802309379902537810/972677133438693456/unknown.png

**Instance#:**
DracV 4

**Comment by Synirrr** [comment]
Not a problem for us
Wont fix
