### ISSUE TITLE
Fixship required to place blocks on ground outpost

### ISSUE THREAD

**Issue by Joyfulasteroid** [DraconisCluster/DracVerse-Issues#28]
**Describe the bug**
Fixship required to place blocks on ground outpost if you haven't fixshipped in the last 5 mins or so

**To Reproduce**
1. Have a ground outpost
2. try to place a block

**Expected behavior**
Block that is allowed on that core is placed

**Actual behaviour**:
You get "unable to place" error

**Instance#: DV7

**Comment by Synirrr** [comment]
Duplicate of [Issue44](https://github.com/DraconisCluster/DracVerse-Issues/issues/44)
