### ISSUE TITLE
Cores not scrollable despites claiming so on icon

### ISSUE THREAD

**Issue by kontu** [DraconisCluster/DracVerse-Issues#3]
**Describe the bug**
Several cores show a + sign signifying you can scroll-wheel them for other blocks. They do not scrollywheel.
The basic core at least swaps between basic+util

**To Reproduce**
Put a core with a + sign on hotbar, scroll mousewheel

**Expected behavior**
Scroll through types of core

**Screenshots**
 ![image](https://user-images.githubusercontent.com/5705697/167207511-a4294807-3ab6-400c-af09-e70208b4746f.png)

**Instance#:** dv6 / Not applicable

**Comment by TheCodedOne** [comment]
This is because the cores that you scroll too havent been researched yet, once they're researched you'll be able to scroll them
