### ISSUE TITLE
Utiliy core bounding box

### ISSUE THREAD

**Issue by Joyfulasteroid** [DraconisCluster/DracVerse-Issues#30]
**Describe the bug**
Utiliy core bounding box is wrong

**To Reproduce**
1.Try to place a utility core, not limited to subgrids

**Expected behavior**
Bounding box matches block size

**Screenshots**

**Instance#:** DV7

**Additional context**
![Screenshot_220](https://user-images.githubusercontent.com/79765295/167299920-cca69e8f-2f01-464c-9b01-76daec3f24d3.png)
![Screenshot_219](https://user-images.githubusercontent.com/79765295/167299921-2760d84d-7671-44fe-a6bf-e472b27710bd.png)

**Comment by Synirrr** [comment]
Will be fixed on release
