### ISSUE TITLE
Trade station docking

### ISSUE THREAD

**Issue by Kamikazie** [DraconisCluster/DracVerse-Issues#35]
**Describe the bug**
The trade station will only let you dock if you own the grid. If the grid is shared with faction and you do not own the grid you can not dock. See the screenshot attached where one side is the share with faction who has a white connector and the other side is yellow who owns the grid.

**To Reproduce**
1. Go to trade station and try to dock

**Expected behavior**
You should be able to dock and trade with a shared grid, not just grids you own.

**Screenshots**
![image](https://user-images.githubusercontent.com/18252940/167319352-afd0d02a-4181-4f51-a837-f6301ab8271a.png)

**Instance#:** DV6

**Additional context**

**Comment by Synirrr** [comment]
This is keen code not something we have direct control over. We may include it in a performance update down the road
