### ISSUE TITLE
issues with Core

### ISSUE THREAD

**Issue by Poksmote** [DraconisCluster/DracVerse-Issues#36]
can not place any core leading to cannot place any block.

**To Reproduce**
1. get on server
2. spawn into world
3. try to build
4. it dosnt work for me

**Expected behavior**
to be able to build but cant evev place a armor block.

**Screenshots**

**Instance#: DracV4

**Additional context**
i cant place any block or core on a grid.
it gives me a error saying unable to place core, error while finding core for grid.

**Comment by Synirrr** [comment]
Rectified in later builds
