### ISSUE TITLE
Unable to place new transition armor blocks

### ISSUE THREAD

**Issue by evilking9090** [DraconisCluster/DracVerse-Issues#41]
**Describe the bug**
Unable to place any of the new transition blocks on either a Utility Core grid, or a Outpost Core grid.

Transition blocks:
Light Armor Slope Transition Mirrored
Light Armor Slope Transition Tip Mirrored
Light Armor Slope Transition Base
Light Armor Slope Transition
Light Armor Slope Transition Tip
Light Armor Slope Transition Base Mirrored
And heavy variants 

![image](https://user-images.githubusercontent.com/1501136/167563236-3593604d-1327-47d1-9ede-9ee19b96b077.png)

**Comment by Synirrr** [comment]
Should be fixed with the next deployment of Cores
