### ISSUE TITLE
Cannot place grav gen on factory ship 

### ISSUE THREAD

**Issue by Joyfulasteroid** [DraconisCluster/DracVerse-Issues#45]
**Describe the bug**
Cannot place grav gen on factory ship 

**To Reproduce**
1. Have a ship with factory ship core and try to place grav gen

**Expected behavior**
The grav gen places?

**Instance#: DV7

![Screenshot_227](https://user-images.githubusercontent.com/79765295/167949654-2f0a650d-b756-40e9-977a-c54b626ec82c.png)

**Comment by plutothemad** [comment]
This is also true for basic core, reproduced on DV3

**Comment by Synirrr** [comment]
Fixed with latest release of cores.
