### ISSUE TITLE
Space Outpost core not working

### ISSUE THREAD

**Issue by Joyfulasteroid** [DraconisCluster/DracVerse-Issues#47]
**Describe the bug**
Space outpost core doesnt not register as a core

**To Reproduce**
1. place core. Try to power things placed on it. Try to add more than 20 blocks

**Expected behavior**
It to work
**Instance#: DV7

**Screenshots**
![Screenshot_228](https://user-images.githubusercontent.com/79765295/167951152-a87dba7f-d8b2-4a85-b793-fa66f3af00c0.png)

![Screenshot_230](https://user-images.githubusercontent.com/79765295/167951357-252c99af-5cbc-44a5-a88f-4e1c029e66f5.png)

**Comment by Synirrr** [comment]
Fixed on our side will be fixed for launch
