### ISSUE TITLE
Indestructible ships against collision using wheel suspensions

### ISSUE THREAD

**Issue by Tactech1157** [DraconisCluster/DracVerse-Issues#48]
Using merge blocks to attach wheels to ship cause the ship to become indestructible against collision damage.
The wheel it's self has to be part of your main grid for the effect to take place, this is do to how keen protects the subgrid wheels from collision damage but it doesn't discriminate wheel vs an entire grid when connected this way.

disabling building of blocks on wheels won't prevent this as wheel suspensions can be attached to rotors or any number of other attachable blocks.
![image](https://user-images.githubusercontent.com/105240880/168273314-400a7cb8-c5f8-4574-9410-d4ce8628c136.png)
![image](https://user-images.githubusercontent.com/105240880/168273387-09a6c7e9-5672-40f9-8fbe-1f51eb5b90f0.png)
The seemingly unattached suspension is attached to the wheel on the merge blocks but it teleported behind the helicopter when the merge blocks connected

**Comment by Tactech1157** [comment]
Update...
You don't have to keep the wheel suspension on the ship as long as the original wheel with shaft remains a part of the main grid

**Comment by Synirrr** [comment]
Unable to fix recommend raising a keen bug
