### ISSUE TITLE
Clipping issue with utility core/control panels

### ISSUE THREAD

**Issue by evilking9090** [DraconisCluster/DracVerse-Issues#5]
**Describe the bug**
When placing a control panel on top of a utility core, there is a large airgap.

**To Reproduce**
1. place a control panel on top of a utility core

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1501136/167230310-fb47d7a0-d83d-4663-bd84-47cc5b3a81b5.png)

**Instance#:**
all

**Additional context**

**Comment by Synirrr** [comment]
Will be fixed for release
