### ISSUE TITLE
B&R Vanilla Beacon welding

### ISSUE THREAD

**Issue by evilking9090** [DraconisCluster/DracVerse-Issues#51]
**Describe the bug**
When a Build & Repair attempts to weld a vanilla beacon from a blueprint, the error message displayed "cannot weld core/beacon" broadcasts for the entire instance.

**Comment by Synirrr** [comment]
Oh interesting... In the future you can blacklist those blocks in the build and repair. We will work on making sure the notification is for the player not the server

**Comment by Synirrr** [comment]
This is due to the way Build and Repair performs welding. We will mitigate it by removing beacons and cores from projections.
