### ISSUE TITLE
Keen grid cleanup enabled

### ISSUE THREAD

**Issue by kontu** [DraconisCluster/DracVerse-Issues#53]
**Describe the bug**
Found on DV5 keen grid cleanup is enabled 

**Expected behavior**
Keen grid cleanup should be off. The "suspend" button should say "Enable" to show that it is turned off

**Screenshots**
![image](https://user-images.githubusercontent.com/5705697/168635542-dc093aa9-de97-49a4-9527-60ee955b4a6e.png)

**Instance#:**
dv5, dv6

**Additional context**

**Comment by Synirrr** [comment]
Fixed on lobby and all servers
