### ISSUE TITLE
Unable to place researched components after completing research.

### ISSUE THREAD

**Issue by evilking9090** [DraconisCluster/DracVerse-Issues#55]
**Describe the bug**
After researching Programable blocks, the item "Programable Computer Schematic" appears (I have no idea what this is for).

After research was completed, the ability to see the researched block in the toolbar menu appears (to select the pb and place on a hotbar). When attempting to place down a programable block with the schematic in my inventory, an error message populates with the cores (screenshot 1).

After attempting to place the schematic in any non-scientific machine storage, the message "ADQconstraints" appears over the cursor in the storage inventory (screenshot 2).

I am able to move the schematic between my inventory and research lab, but not a scanner of any sort (I assume that's intentional).
 

**Screenshots**
![image](https://user-images.githubusercontent.com/1501136/169006505-ca1b5ae3-ce03-4abb-983c-197527166d8c.png)
![image](https://user-images.githubusercontent.com/1501136/169007223-5dd29899-284d-46c6-9f37-e7f163fff288.png)

**Instance#:**
DV5

**Comment by Synirrr** [comment]
Fixed in next deployment of core configs
