### ISSUE TITLE
T1 Yield & Speed refinery conveyor ports and attachment points

### ISSUE THREAD

**Issue by ThePrimordialTV** [DraconisCluster/DracVerse-Issues#59]
**Describe the bug**
Non-DLC T1 yield and speed refineries do not have operational conveyor ports, they cannot be accessed by hand nor can they accept items from a directly adjacent cargo. 

Their attachment points are also incorrect as you cannot place anything directly onto a conveyor port and many other points that would be acceptable without additional support. They also do not recognize they have upgrade module slots inside their UI and nor can any be placed on their slots due to above attachment issues. Funnily enough they can be placed on the front of the refinery however but do not function.

**To Reproduce**
1. place refinery
2. attempt to place conveyor
3. fail

**Expected behavior**
Appropriate attachment points and accessible conveyors/access panels 

**Screenshots**

Attachment Points
![Attach](https://media.discordapp.net/attachments/971661179581788190/978773274102235146/unknown.png?width=1118&height=910)

Modules on front
![module](https://media.discordapp.net/attachments/971661179581788190/978773792870510662/unknown.png?width=948&height=910)

**Instance#:**
Creative test world

**Additional context**
I ran through most of the other tier 1 blocks and these were the only 2 that appeared to have any issues.

**Comment by Zardo1** [comment]
Should be fixed with the next push
