### ISSUE TITLE
Instance doesnt show

### ISSUE THREAD

**Issue by Joyfulasteroid** [DraconisCluster/DracVerse-Issues#65]
**Describe the bug**
The instance isn't shown at the top, not sure if this is a nexus thing or an us thing so dismiss if its not an us thing

**To Reproduce**
1. Press F3

**Expected behavior**
Instance name to be shown.....

**Screenshots**
![Screenshot_239](https://user-images.githubusercontent.com/79765295/170823735-e0d48803-02e1-478c-86e4-1b0806d4f8e4.png)

**Instance#: DV12 i think but it doesnt say

**Comment by TheCodedOne** [comment]
This is a seamless bug not something we can fix.
