### ISSUE TITLE
Trade station Access denied issue and Character LCDs Blank

### ISSUE THREAD

**Issue by LeoKeatonn** [DraconisCluster/DracVerse-Issues#76]
**Describe the bug**
Trade station would not let players close the data processing areas because they didnt have access to interact with the door button. Also some of the "NPC" Characters at the station wouldn't display any text when clicked on. Lastly the store didnt contain any buy oreders.

**To Reproduce**
1. Go to satreus moon trade station
2. Try to close data processing door, fails.
3. Try to sell data core, fails
4. Try to sell or buy from shop, fails

**Expected behavior**
Players should have access to the door button, the station should be accepting items as well as sell/buy orders

**Screenshots**
(https://www.youtube.com/watch?v=kvk0V2Kwi7Q&ab_channel=AlexZaccaria)

**Instance#:**
DV7

**Comment by Synirrr** [comment]
Stations do not buy or sell at the moment. All you need to do is process the datacores in the assemblers
