### ISSUE TITLE
Missing ADQ conveyors

### ISSUE THREAD

**Issue by ThePrimordialTV** [DraconisCluster/DracVerse-Issues#8]
Seems the ADQ armored conveyors didn't make it through to the test server, while we do at least have vanilla reinforced conveyors they are crucially lacking an X junction. 

We also still have the extra conveyors like elbows and endcaps in the ADQ style in the current coremod.

**Comment by TheCodedOne** [comment]
X style reinforced conveyors are coming soon through our deco mod, just havent been moved over yet.

**Comment by Synirrr** [comment]
Intentional we will update the conveyor mod that Zardo created to include an X junction
